version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:8.16.0
    environment:
      NODE_ENV: development
    working_directory: ~/animare.cafe

commands:
  yarn_install:
    steps:
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-

      - run:
          command: yarn install --frozen-lockfile
          name: yarn install

      - save_cache:
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - yarn_install
      - persist_to_workspace:
          paths:
            - ./*
          root: .

  lint:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint

  build:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run: yarn build

  deploy:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run: NODE_ENV=production yarn generate
      - run: npx firebase-tools deploy --only hosting --token $FIREBASE_TOKEN

workflows:
  version: 2
  workflow:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - lint
            - build
          filters:
            tags:
              only: /^v\d+(?:\.\d+){0,2}$/
            branches:
              ignore: /.*/
