version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:8.12.0
    environment:
      NODE_ENV: development
    working_directory: ~/animare.cafe

commands:
  yarn_install:
    steps:
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - yarn_install
      - run: yarn lint

  deploy:
    executor:
      name: default
    steps:
      - checkout
      - yarn_install
      - run: yarn generate
      - run: npx firebase-tools deploy --token $FIREBASE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
