version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:8.12.0
    environment:
      NODE_ENV: development
    working_directory: ~/animare.cafe

commands:
  yarn_install:
    steps:
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-

      - run:
          command: yarn install --frozen-lockfile
          name: yarn install

      - save_cache:
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/

      - restore_cache:
          keys:
            - v1-functions-dependencies-{{ checksum "functions/yarn.lock" }}
            - v1-functions-dependencies-

      - run:
          name: yarn install (functions)
          command: yarn install --frozen-lockfile
          working_directory: ./functions/

      - save_cache:
          key: v1-functions-dependencies-{{ checksum "functions/yarn.lock" }}
          paths:
            - ./functions/node_modules/

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - yarn_install
      - run: yarn lint
      - run: yarn build

  deploy:
    executor:
      name: default
    steps:
      - checkout
      - yarn_install
      - run: NODE_ENV=production yarn generate
      - run: npx firebase-tools deploy --only hosting,functions --token $FIREBASE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
